"""Initial models

Revision ID: 054dfb9f30d0
Revises: 
Create Date: 2026-07-17 17:33:37.187585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '054dfb9f30d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('game_creation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_duration', sa.Integer(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.Column('queue_name', sa.String(), nullable=True),
    sa.Column('patch', sa.String(), nullable=True),
    sa.Column('raw_match_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_timeline_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('riot_id', sa.String(), nullable=False),
    sa.Column('tag_line', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('preferred_queue', sa.Integer(), nullable=True),
    sa.Column('preferred_role', sa.String(), nullable=True),
    sa.Column('goals_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_puuid'), 'players', ['puuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_puuid'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
