"""Add vision metrics gold_diff_25 and support_cs_alert

Revision ID: 0ef7452f38cf
Revises: 53e8f5fae9eb
Create Date: 2026-07-29 09:48:45.599789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef7452f38cf'
down_revision: Union[str, Sequence[str], None] = '53e8f5fae9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match_metrics', sa.Column('gold_diff_25', sa.Float(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('wards_placed', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('wards_killed', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('vision_wards_bought', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('vision_score_advantage', sa.Float(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('support_cs_alert', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match_metrics', 'support_cs_alert')
    op.drop_column('player_match_metrics', 'vision_score_advantage')
    op.drop_column('player_match_metrics', 'vision_wards_bought')
    op.drop_column('player_match_metrics', 'wards_killed')
    op.drop_column('player_match_metrics', 'wards_placed')
    op.drop_column('player_match_metrics', 'gold_diff_25')
    # ### end Alembic commands ###
