"""Add situational_analysis_json to PlayerMatchMetrics

Revision ID: 13c1b45f5f59
Revises: 98bdb73adf30
Create Date: 2026-07-29 02:15:50.836549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13c1b45f5f59'
down_revision: Union[str, Sequence[str], None] = '98bdb73adf30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match_metrics', sa.Column('situational_analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match_metrics', 'situational_analysis_json')
    # ### end Alembic commands ###
