"""Add advanced metrics columns

Revision ID: 53e8f5fae9eb
Revises: 13c1b45f5f59
Create Date: 2026-07-29 02:22:33.820881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e8f5fae9eb'
down_revision: Union[str, Sequence[str], None] = '13c1b45f5f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match_metrics', sa.Column('team_damage_percentage', sa.Float(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('damage_mitigated', sa.Float(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('heal_shield_effective', sa.Float(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('cc_time', sa.Float(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('turret_plates', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match_metrics', 'turret_plates')
    op.drop_column('player_match_metrics', 'cc_time')
    op.drop_column('player_match_metrics', 'heal_shield_effective')
    op.drop_column('player_match_metrics', 'damage_mitigated')
    op.drop_column('player_match_metrics', 'team_damage_percentage')
    # ### end Alembic commands ###
