"""Add metrics and insights models

Revision ID: 98bdb73adf30
Revises: 054dfb9f30d0
Create Date: 2026-07-17 20:09:16.144897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98bdb73adf30'
down_revision: Union[str, Sequence[str], None] = '054dfb9f30d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('generated_analysis', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_player_id'), 'insights', ['player_id'], unique=False)
    op.create_table('player_match_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('champion', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('cs_per_min', sa.Float(), nullable=True),
    sa.Column('gold_per_min', sa.Float(), nullable=True),
    sa.Column('vision_per_min', sa.Float(), nullable=True),
    sa.Column('kill_participation', sa.Float(), nullable=True),
    sa.Column('deaths_before_objectives', sa.Integer(), nullable=True),
    sa.Column('gold_diff_10', sa.Float(), nullable=True),
    sa.Column('gold_diff_15', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_match_metrics_match_id'), 'player_match_metrics', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_match_metrics_player_id'), 'player_match_metrics', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_match_metrics_player_id'), table_name='player_match_metrics')
    op.drop_index(op.f('ix_player_match_metrics_match_id'), table_name='player_match_metrics')
    op.drop_table('player_match_metrics')
    op.drop_index(op.f('ix_insights_player_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
