"""Add advanced metrics

Revision ID: 9f60474d84bf
Revises: 0ef7452f38cf
Create Date: 2026-08-03 06:33:05.407179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f60474d84bf'
down_revision: Union[str, Sequence[str], None] = '0ef7452f38cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_match_metrics', sa.Column('solo_kills', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('lane_minions_first_10_minutes', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('max_cs_advantage_on_lane_opponent', sa.Float(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('max_level_lead_lane_opponent', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('jungle_cs_before_10_minutes', sa.Float(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('epic_monster_steals', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('scuttle_crab_kills', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('epic_monster_kills_near_enemy_jungler', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('ward_takedowns_before_20m', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('save_ally_from_death', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('skillshots_dodged', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('skillshots_hit', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('outnumbered_kills', sa.Integer(), nullable=True))
    op.add_column('player_match_metrics', sa.Column('kills_near_enemy_turret', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_match_metrics', 'kills_near_enemy_turret')
    op.drop_column('player_match_metrics', 'outnumbered_kills')
    op.drop_column('player_match_metrics', 'skillshots_hit')
    op.drop_column('player_match_metrics', 'skillshots_dodged')
    op.drop_column('player_match_metrics', 'save_ally_from_death')
    op.drop_column('player_match_metrics', 'ward_takedowns_before_20m')
    op.drop_column('player_match_metrics', 'epic_monster_kills_near_enemy_jungler')
    op.drop_column('player_match_metrics', 'scuttle_crab_kills')
    op.drop_column('player_match_metrics', 'epic_monster_steals')
    op.drop_column('player_match_metrics', 'jungle_cs_before_10_minutes')
    op.drop_column('player_match_metrics', 'max_level_lead_lane_opponent')
    op.drop_column('player_match_metrics', 'max_cs_advantage_on_lane_opponent')
    op.drop_column('player_match_metrics', 'lane_minions_first_10_minutes')
    op.drop_column('player_match_metrics', 'solo_kills')
    # ### end Alembic commands ###
